version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=your_password_here

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:latest
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      - NEO4J_AUTH=neo4j/your_password_here

  frontend:
    build:
      context: ./src/frontend
    ports:
      - "8501:8501"
    volumes:
      - ./src/frontend:/app/src/frontend
    depends_on:
      - backend